config/routes.rb
Rails.application.routes.draw do
  root to: 'events#index'
  devise_for :users

  resources :static_pages
  resources :events
  resources :attendances
  resources :users, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event

  after_create :confirmation_to_admin_send

  def confirmation_to_admin_send
    puts self.user
    UserMailer.confirmation_attendance_email(self.user).deliver_now
  end

end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :administrator, class_name: "User"
  has_many :attendances
  has_many :users, through: :attendances

  validates :title,
    presence: true,
    length: { minimum: 5, maximum: 140 }

  validates :start_date, 
    presence: true
  validate :start_date_cannot_be_in_the_past

  def start_date_cannot_be_in_the_past
    if start_date <= Date.current
      errors.add(:start_date, "La date de début de l'évênement doit se situer dans le futur !")
    end
  end

  validates :duration, 
    presence: true, 
    numericality: { only_integer: true, greater_than: 0 }
  validate :duration_should_be_multiple_of_5

  def duration_should_be_multiple_of_5
    if duration % 5 != 0
      errors.add(:duration, "Un évênement doit avoir une durée multiple de 5 minutes !")
    end
  end

  validates :price,
    presence: true,
    numericality: { only_integer: true, greater_than: 1, less_than: 1000 }

  validates :description,
    presence: true,
    length: { minimum: 5, maximum: 140 }

  validates :location,
    presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events, through: :attendances

  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController

  def new
    @event = Event.find_by(id: params[:event_id])
    @attendance = Attendance.new
  end

  def show
    @attendance = Attendance.find(params[:id])
  end

  def create
    @attendance = Attendance.new(stripe_customer_id: "########", event_id: params[:event_id], user_id: params[:id])
    if @attendance.save 
      redirect_to root_path
    else
      flash.now[:danger] = 'Invalid attendance parameters !'
      render 'new'
    end
  end

end

app/controllers/event_controller.rb
class EventController < ApplicationController

  def index

  end

  def create

  end
  
  def show
    @event = Event.find_by(id: params[:id])
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index

  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(title: params[:title], start_date: params[:start_date], duration: params[:duration], location: params[:location], price: params[:price], description: params[:description], administrator_id: current_user.id)
    if @event.save 
      redirect_to root_path
    else
      flash.now[:danger] = 'Invalid event parameters !'
      render 'new'
    end
  end
  
  def show
    @event = Event.find_by(id: params[:id])
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def secret
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendance_helper.rb
module AttendanceHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/attendances/new.html.erb
<div class="container">
  <div class="row my-5 text-center text-success">
    <h1>Page d'inscription à un évênement</h1>
    
    <div class="card shadow-lg bg-dark text-light mx-auto my-5" style="width: 24rem;">
      <div class="card-body">
        <h5 class="card-title"> <%= @event.title %> </h5>
        <h6 class="card-subtitle mb-2 text-warning"> <%=  @event.start_date.strftime('%Y %m %d %H:%M') %> </h6>
        <h6 class="card-subtitle mb-2 text-primary"> <%=  @event.location %> </h6>
        <h6 class="card-subtitle mb-2 text-muted"> <%=  @event.duration %> minutes </h6>
        <h6 class="card-subtitle mb-2 text-muted"> Organisateur: <%=  @event.administrator.first_name %> </h6>
        <p class="card-text"> <%=  @event.description %> </p>
        <h6 class="card-subtitle mb-2 text-muted"> <%=  @event.price %> €  </h6>
        
        <% user_participates = false %>
        <% @event.attendances.each do |a| %>
          <% if a.user_id == current_user.id %>
            <p class="text-center text-success">Vous êtes inscrit à cet évênement !</p>
            <% user_participates = true %>             
          <% end %>
        <% end %>
        <% unless user_participates %>
          <%= link_to "Confirmer l'inscription", attendances_path(event_id: @event.id, id: current_user.id), method: :post, class: "btn btn-outline-light my-5 w-100" %>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/attendances/show.html.erb
<p> Hello dude </p>

app/views/events/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="p-5 text-center bg-image" style="background-image: url('assets/crowd.jpg'); height: 600px;">
      <div class="mask m-5 p-3" style="border-radius: 33px; background-color: rgba(0, 0, 0, 0.51);">
        <div class="d-flex justify-content-center align-items-center h-100">
          <div class="text-white">
            <h4 class="my-5">Rejoignez l'énergie qui vous entoure !</h4>
            <% if current_user %>
              <%= link_to "Créer un évênement", new_event_path, class: "btn btn-outline-light btn-lg mb-5" %>
            <% else %>
              <%= link_to "Créer un évênement", new_user_session_path, class: "btn btn-outline-light btn-lg mb-5" %>
            <% end %>  
          </div>
        </div>
      </div>
      </div>
    </div> 
  </div>
  <div class="row mx-5">
    <% Event.all.each do |e| %>
      <div class="col mx-2">
        <div class="card shadow-lg bg-dark text-light mx-auto my-5 p-4" style="width: 22rem; height: 500px; border-radius: 22px;">
          <div class="card-body d-flex flex-column">
            <h5 class="card-title text-light text-end mb-3"> <%= e.title %> </h5>
            <h6 class="card-subtitle mb-5 text-warning text-end"> <%= e.start_date.strftime('%Y %m %d %H:%M') %> </h6>
            <h6 class="card-subtitle my-2 text-primary text-start"> <%= e.location %> </h6>
            <h6 class="card-subtitle mb-2 text-secondary"> <%= e.duration %> minutes </h6>
            <p class="card-text text-light mt-3"> <%= e.description %> </p>
            <div class="mt-auto">
            <h6 class="card-subtitle mb-2 text-success text-center"> <%= e.price %> €  </h6>
            <h6 class="card-subtitle mb-2 text-secondary text-center text-muted"> Organisateur: <%= e.administrator.first_name %> </h6>
            <h6 class="card-subtitle mb-2 text-success text-center"> Déjà <%= e.attendances.length %> participants </h6>
            <% if current_user %>
              <%= link_to "Voir l'évênement", event_path(:id => e.id), class: "btn btn-outline-light w-100  my-3" %>
            <% else %>
              <%= link_to "Voir l'évênement", new_user_session_path, class: "btn btn-outline-light w-100 my-3" %>
            <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<div class="list-group-item w-75 mx-auto text-center mt-5">
  <h2 class="my-5">Création d'un évênement</h2>
  <%= form_tag url_for(action: 'create'), method: "post" do %>
    <div class="event-creation__title"> 
      <%= label_tag 'Titre' %>
      <%= text_field_tag 'title', @event.title %>
    </div>
    <div class="event-creation__title"> 
      <%= label_tag 'Date de début' %>
      <%= date_field_tag 'start_date', @event.start_date %>
    </div>
    <div class="event-creation__title"> 
      <%= label_tag 'Durée (en minutes)' %>
      <%= text_field_tag 'duration', @event.duration %>
    </div>
    <div class="event-creation__title"> 
      <%= label_tag 'Lieu' %>
      <%= text_field_tag 'location', @event.location %>
    </div>
    <div class="event-creation__title"> 
      <%= label_tag 'Prix' %>
      <%= text_field_tag 'price', @event.price %>
    </div>
    <div class="event-creation__content"> 
      <%= label_tag 'Description' %>
      <%= text_area_tag 'description', @event.description %>
    </div>
    <div class="my-5 event-creation__submit-button">
      <%= submit_tag "Créer l'évênement" %>
    </div>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div class="card shadow-lg bg-dark text-light mx-auto my-5" style="width: 24rem;">
        <div class="card-body">
          <h5 class="card-title"> <%= @event.title %> </h5>
          <h6 class="card-subtitle mb-2 text-warning"> <%=  @event.start_date.strftime('%Y %m %d %H:%M') %> </h6>
          <h6 class="card-subtitle mb-2 text-primary"> <%=  @event.location %> </h6>
          <h6 class="card-subtitle mb-2 text-muted"> <%=  @event.duration %> minutes </h6>
          <h6 class="card-subtitle mb-2 text-muted"> Organisateur: <%=  @event.administrator.first_name %> </h6>
          <p class="card-text"> <%=  @event.description %> </p>
          <h6 class="card-subtitle mb-2 text-muted"> <%=  @event.price %> €  </h6>
          
          <% user_participates = false %>
          <% @event.attendances.each do |a| %>
            <% if a.user_id == current_user.id %>
              <p class="text-center text-success">Vous êtes inscrit à cet évênement !</p>
              <% user_participates = true %>             
            <% end %>
          <% end %>
          <% unless user_participates %>
            <%= link_to "S'inscrire", new_attendance_path(event_id: @event.id), class: "btn btn-outline-light my-5 w-100" %>
          <% end %> 
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <% if @event.administrator == current_user %>
      <p class="text-center text-primary">Vous êtes administrateur de cet évênement !</p>
      <p class="text-center">Voici la liste des participants incrits :</p>
      <% @event.users.each do |u| %>
        <div class="col">
          <div class="card shadow-lg bg-dark text-light mx-auto my-5" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title"> <%= u.first_name %> <%= u.last_name %></h5>
              <h6 class="card-subtitle mb-2 text-warning"> <%= u.email %> </h6>
              <p class="card-text"> <%= u.description %> </p>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>  
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FuzeNow</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
  </head>

  <body>

  <header>
      <nav class="navbar navbar-dark bg-dark p-3">
        <h2> <%= link_to "FuzeNow", root_path, class: "no-underline text-light mx-4" %> </h2>
        <form class="form-inline">
          <% if user_signed_in? %>
            <%= link_to "Créer un Evênement", new_event_path, class: "no-underline text-light mx-3" %>
            <%= link_to "MoN ProFiL", user_path(id: current_user.id), class: "text-light btn btn-outline-primary mx-3" %>
            <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "btn btn-outline-warning mx-3" %>
          <% else %>
            <%= link_to "Inscription", new_user_registration_path, class: "text-light btn btn-outline-primary mx-3" %>
            <%= link_to "Connexion", new_user_session_path, class: "btn btn-outline-warning" %>  
          <% end %>
        </form>
      </nav>
    </header>

    <%= yield %>

  </body>
</html>

app/views/static_pages/index.html.erb
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>

app/views/users/show.html.erb
<div class="container">

  <div class="row">
    <h2 class="mt-5 text-center text-success">Les évênements auxquels vous participez :</h2>
    <% Attendance.all.each do |a| %>
      <% if a.user_id == current_user.id && a.event.administrator != current_user %>
        <% e = a.event %>
        <div class="col">
          <div class="card shadow-lg bg-dark text-light mx-auto my-5" style="width: 24rem;">
            <div class="card-body">
              <h5 class="card-title"> <%= e.title %> </h5>
              <h6 class="card-subtitle mb-2 text-warning"> <%=  e.start_date.strftime('%Y %m %d %H:%M') %> </h6>
              <h6 class="card-subtitle mb-2 text-primary"> <%=  e.location %> </h6>
              <h6 class="card-subtitle mb-2 text-muted"> <%=  e.duration %> minutes </h6>
              <h6 class="card-subtitle mb-2 text-muted"> Organisateur: <%=  e.administrator.first_name %> </h6>
              <p class="card-text"> <%=  e.description %> </p>
              <h6 class="card-subtitle mb-2 text-muted"> <%=  e.price %> €  </h6>
              <%= link_to "Voir la fiche", event_path(:id => e.id), class: "btn btn-outline-light my-5 w-100" %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="row">
    <h2 class="mt-5 text-center text-success">Les évênements que vous organisez :</h2>
    <% Attendance.all.each do |a| %>
      <% if a.user_id == current_user.id && a.event.administrator == current_user %>
        <% e = a.event %>
        <div class="col">
          <div class="card shadow-lg bg-dark text-light mx-auto my-5" style="width: 24rem;">
            <div class="card-body">
              <h5 class="card-title"> <%= e.title %> </h5>
              <h6 class="card-subtitle mb-2 text-warning"> <%=  e.start_date.strftime('%Y %m %d %H:%M') %> </h6>
              <h6 class="card-subtitle mb-2 text-primary"> <%=  e.location %> </h6>
              <h6 class="card-subtitle mb-2 text-muted"> <%=  e.duration %> minutes </h6>
              <h6 class="card-subtitle mb-2 text-muted"> Organisateur: <%=  e.administrator.first_name %> </h6>
              <p class="card-text"> <%=  e.description %> </p>
              <h6 class="card-subtitle mb-2 text-muted"> <%=  e.price %> €  </h6>
              <%= link_to "Voir la fiche", event_path(:id => e.id), class: "btn btn-outline-light my-5 w-100" %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="row text-center">
    <div class="col">
      <%= link_to "Editer MoN ProFiL", edit_user_registration_path, class: "btn btn-outline-primary my-5" %>
    </div>
  </div>
</div>